### ISSUE TITLE
New runs failing since merge of 886a0ce

### ISSUE THREAD

**Issue by mattlehrer** [nanos/FediFetcher#35]
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/261396/230014633-3bc48063-06dc-4b5d-b943-63c72d69b372.png">

I am seeing this error:

>   File "/home/runner/work/mastodon_get_replies/mastodon_get_replies/find_posts.py", line 756, in <module>
    arguments.lock_file = os.path.join(arguments.state, 'lock.lock')
AttributeError: 'Namespace' object has no attribute 'state'

**Comment by lilfade** [comment]
Was coming to do just this, experiencing as well.

**Comment by quicoto** [comment]
Same

https://github.com/quicoto/mastodon-get-replies/actions/runs/4616214140/jobs/8160941063

**Comment by nanos** [comment]
Apologies everyone. That should now be fixed, without needing further action

**Comment by nanos** [comment]
Some correction to the 'without needing further action' part:

If you are running a GitHub Action you need not take any further action.

If you are running a cron job, you'll need to get the latest version of `find_posts.py` and remove `artifacts/lock.lock`.
