### ISSUE TITLE
"NoMethodError: undefined method `[]' for nil:NilClass" Showing up in Queues

### ISSUE THREAD

**Issue by Xipherisroot** [nanos/FediFetcher#36]
Since upgrading from 3.0.1 to 4.1.6, suddenly I'm seeing dead/retry jobs in my sidekiq queues of a strange nature that seem to coincide with scheduled runs of FediFetcher

In the ingress queue, I get jobs that show as:

> ActivityPub::ProcessingWorker - <18 digit number here>, "null", nil, "Account" - NoMethodError: undefined method `[]' for nil:NilClass

No errors like this before updating the script and changing the arguments to the new style from the old style, not sure what would be causing it but since it started happening exactly as soon as I changed the script and no other changes have been made, I'd suppose it has to do with the script making a bad call?

Curious whats going on here... I see later releases today but nothing in the patch notes that seems to denote this problem?

**Comment by nanos** [comment]
Thanks for the report @Xipherisroot 

I do have to say that I cannot imagine how this could possibly be a problem with FediFetcher:

 - FediFetcher uses only endpoints that provide synchronous results. AFAIK it shouldn't involve sidekiq at all.
 - I'm not seeing the error in my sidekiq logs, and noone else has reported this.
 - FediFetcher is not pulling in any accounts, only posts, so the reference to accounts would be weird too.

Finally, FediFetcher doesn't touch mastodon code directly. It merely uses the Mastodon API. As such, even if it did cause this behaviour, it would be a bug that would need to be fixed within Mastodon, as we are using the API as documented.

As such I'll close this for now.

If you or anyone else has any further insight, I'm more than happy to revisit this though.

**Comment by AndrewKvalheim** [comment]
This happened to me when running 4.1.3 but I haven’t seen it since updating to 4.1.9.

**Comment by Xipherisroot** [comment]
I've updated to 4.1.9 myself and so far on a few runs... its gone away, if it happens again during a run I'll report back? Glad I'm not the only one that noticed it though how it was caused... dunno'

I do know that I get a ton of "Got context for toot None" messages when run, not sure how it can get context for "None"...?

**Comment by AndrewKvalheim** [comment]
Yep every run has many of these:

```
2023-04-05 20:51:48.154387 UTC: Got context for toot None
2023-04-05 20:51:48.526278 UTC: Got context for toot None
2023-04-05 20:51:49.855136 UTC: Got context for toot None
2023-04-05 20:51:50.181248 UTC: Got context for toot None
2023-04-05 20:51:50.775495 UTC: Got context for toot None
2023-04-05 20:51:51.658244 UTC: Got context for toot None
2023-04-05 20:51:52.012641 UTC: Got context for toot None
2023-04-05 20:51:52.284524 UTC: Got context for toot None
2023-04-05 20:51:53.069537 UTC: Got context for toot None
```

Haven’t looked into it yet but I also want to confirm what the script does when [`LOCAL_DOMAIN`](https://docs.joinmastodon.org/admin/config/#local_domain)≠[`WEB_DOMAIN`](https://docs.joinmastodon.org/admin/config/#web_domain).

**Comment by nanos** [comment]
> This happened to me when running 4.1.3 but I haven’t seen it since updating to 4.1.9.

This is very strange, as I cannot think of anything that could cause this. But I'm glad it's gone now. Hoping it'll stay gone.

> if it happens again during a run I'll report back?

Please do.

> Got context for toot None

This is expected to happen when FediFetcher can't parse a toot URL, and therefore we cannot fetch context / replies to those posts. I'm happy to accept PRs that would expand the parsing capabilities for both [profiles](https://github.com/nanos/FediFetcher/blob/b9d82dc07317164b05fd89ee48aeccf4bcc5a580/find_posts.py#L421) and [posts](https://github.com/nanos/FediFetcher/blob/b9d82dc07317164b05fd89ee48aeccf4bcc5a580/find_posts.py#L438)

> Haven’t looked into it yet but I also want to confirm what the script does when [LOCAL_DOMAIN](https://docs.joinmastodon.org/admin/config/#local_domain)≠[WEB_DOMAIN](https://docs.joinmastodon.org/admin/config/#web_domain).

It will pull in context/replies just fine, but it will likely fail backfilling profiles. I've opened #38 to track this.
